[AdditionalOptions]
fastUser_switching           = 0
home                         = 0
lyric_always_show            = 1
radio                        = 0
visualization_high_framerate = 0
lyric_force_no_sync          = 0
song_page                    = 0
sidebar_config               = 0
home_config                  = 1
experimental_features        = 1
custom_apps                  = new-releases|name-that-tune|better-local-files|marketplace|lyrics-plus|visualizer|history-in-sidebar|eternal-jukebox
extensions                   = 

[Patch]

[Setting]
prefs_path              = /Users/Mccranky/Library/Application Support/Spotify/prefs
current_theme           = Comfy
color_scheme            = Everforest
inject_theme_js         = 1
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
spotify_launch_flags    = 
spotify_path            = /Applications/Spotify.app/Contents/Resources
check_spicetify_upgrade = 1
check_spicetify_update  = 1
always_enable_devtools  = 0

[Preprocesses]
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.61.443.gc51c574b
with    = 2.42.1
